apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: health-export
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
    component: cache