apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: health-export
  labels:
    app: postgresql
    component: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
    component: database

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: health-export
  labels:
    app: postgresql
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
    component: database